services: 
  app:
    build:
      context: ./app
    container_name: app
    networks:
      - node-network
    volumes:
      - ./app:/app
    entrypoint: sh -c "npm install && npm start"
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./app/db_init:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 3



  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    ports:
      - "8080:80"
    networks: 
      - node-network
    depends_on:
      - app


networks: 
  node-network:
    driver: bridge 